# Generated by Django 3.2.9 on 2021-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0003_alter_shop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(max_length=255, upload_to='img/%Y/%m/%d/'),
        ),
    ]
