# Generated by Django 3.2.9 on 2021-11-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0006_alter_shop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
